version: '3.8'

services:
  fhirbase:
    user: postgres
    image: fhirbase/fhirbase:latest
    container_name: fhirbase
    ports:
      - "5432:5432"
    volumes:
      - fb-data:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build:
      context: .
    container_name: tcc-project
    ports:
      - "9090:9090"
    env_file:
      - .env

volumes:
  fb-data:
