export const errors = {
  _tag: "Left",
  left: [
    "Invalid id",
    "City name cannot be empty",
    "Invalid lines",
    "Invalid postal code",
    "Invalid state",
    "Invalid address use",
    "Birthdate must be in the past",
    "Invalid CPF",
    "Invalid email",
    "Invalid contact use",
    "Invalid gender type",
    "Invalid first name",
    "Invalid last name",
    "Invalid phone number",
    "Invalid contact use",
  ],
};
